In [1]:
import pandas as pd

passengers = pd.read_csv("train.csv")
print(passengers.shape)
print(passengers.head())

(891, 12)
   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN    

In [3]:
passengers['Sex'] = passengers['Sex'].map({'female':1,'male':0})  #문자열을 숫자로 변환
passengers['Age'].fillna(value=passengers['Age'].mean(), inplace=True) #결측치 채워주기

#feature 분리하기
passengers['FirstClass'] = passengers['Pclass'].apply(lambda x:1 if x==1 else 0)
passengers['SecondClass'] = passengers['Pclass'].apply(lambda x:1 if x==1 else 0)

#dataset
features = passengers[['Sex', 'Age', 'FirstClass', 'SecondClass']]
survival = passengers['Survived']

In [4]:
#학습세트와 평가세트 분석
from sklearn.model_selection import train_test_split

train_features, test_features, train_labels, test_labels = train_test_split(features, survival)

In [6]:
#data 정규화
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
train_features = scaler.fit_transform(train_features)
test_features = scaler.transform(test_features)

In [8]:
#model 생성
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(train_features, train_labels)
print(model.score(train_features, train_labels))
print(model.score(test_features, test_labels))
print(model.coef_, model.intercept_)

0.7664670658682635
0.8161434977578476
[[ 1.21567264 -0.40581948  0.37700621  0.37700621]] [-0.56844717]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [12]:
#예측하기
import numpy as np

Jack = np.array([0.0, 60.0, 0.0, 0.0])
Rose = np.array([0.0, 67.0, 1.0, 0.0])
Me = np.array([0.0, 64.0, 1.0, 0.0])

sample = np.array([Jack, Rose, Me])
sample = scaler.transform(sample)
print(model.predict(sample))

[0 0 0]


In [13]:
print(model.predict_proba(sample))

[[0.94590731 0.05409269]
 [0.89995294 0.10004706]
 [0.89127378 0.10872622]]
